




import Header from "./_components/Header";
import { Inter } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "@fancyapps/ui/dist/fancybox/fancybox.css";
import "bootstrap/dist/css/bootstrap.min.css";
// import 'bootstrap/dist/js/bootstrap.bundle.js';
import "./globals.css";
import { ProfileProvider } from "@/ContextFiles/ProfileContext";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Game App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProfileProvider>
        <Header/>
        {children}
        <Footer/>
        </ProfileProvider>
        </body>

    </html>
  );
}
